name: Code Smell Check 2
on: [push, pull_request]
jobs:
  smell-check-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "manele-se/code-smell-tool@v1.0.0"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
#   smell-check-mac:
#     name: Mac
#     runs-on: macos-latest
#     steps:
#       - uses: "actions/checkout@v2"
#       - uses: "manele-se/code-smell-tool@v1.0.0"
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#   smell-check-windows:
#     name: Windows
#     runs-on: windows-latest
#     steps:
#       - uses: "actions/checkout@v2"
#       - uses: "manele-se/code-smell-tool@v1.0.0"
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
