name: Code Smell Check 2
on: [push, pull_request]
jobs:
  smell-check:
    name: Code Smell Check 2
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "manele-se/code-smell-tool@v0.1.1"
        with:
          source-location: src
